//! The Rust decoder must reproduce what Python derived, from the Lean bundle alone.
//!
//! Vectors are generated by `python -m lmg_format.make_vectors` through the real
//! LMGModel / LMGModelHover code paths.
//!
//! # On tolerances
//!
//! Bit-exactness across implementations is not achievable here, and asserting it
//! would be a false test. torch's reduction order (mean of 3, dot products,
//! norms) is its own; numpy and Rust each accumulate differently at the ULP
//! level. Two places in `prepare_scaling_rot` amplify that:
//!
//! * `scaling` is stored as `log(s + 1e-8)`, and `d(log)/ds = 1/s`. Real meshes
//!   have thin triangles where `s ~ 1e-4`, so one ULP becomes ~1e-4 in log
//!   space. Compared in linear space instead, agreement is ~2e-7.
//! * `rotation` is a quaternion built from a Gram-Schmidt frame. On
//!   near-degenerate faces (`|normal| ~ 1e-5`, and this mesh has them) that
//!   frame is ill-conditioned, so the tail reaches ~7e-5 while the median stays
//!   ~6e-7. A quaternion error of 7e-5 is a rotation error of ~0.008 degrees.
//!
//! So each field carries a max tolerance sized from measurement AND a median
//! tolerance. The median is the regression guard: a genuine port bug (wrong
//! transpose, wrong argmax branch, wrong activation) shifts the whole
//! distribution and cannot hide in the tail.

use lmg_format::{write_params, Bundle, Variant};
use safetensors::tensor::SafeTensors;
use std::path::{Path, PathBuf};

/// (field, max tolerance, median tolerance, compare in linear space)
const FIELDS: [(&str, f32, f32, bool); 3] = [
    ("xyz", 1e-6, 1e-6, false),
    ("scaling", 1e-6, 1e-6, true),
    ("rotation", 1e-3, 1e-5, false),
];

fn vectors_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/vectors")
}

fn read_expected(path: &Path, name: &str, width: usize) -> Vec<Vec<f32>> {
    let raw = std::fs::read(path).expect("expected.safetensors missing");
    let st = SafeTensors::deserialize(&raw).unwrap();
    let t = st.tensor(name).unwrap();
    t.data()
        .chunks_exact(4)
        .map(|c| f32::from_le_bytes([c[0], c[1], c[2], c[3]]))
        .collect::<Vec<f32>>()
        .chunks_exact(width)
        .map(|c| c.to_vec())
        .collect()
}

/// Per-row max error, reduced to (max, median) over rows.
fn errors(got: &[Vec<f32>], want: &[Vec<f32>], linear: bool) -> (f32, f32) {
    assert_eq!(got.len(), want.len(), "row count differs");
    let f = |x: f32| if linear { x.exp() } else { x };
    let mut per_row: Vec<f32> = got
        .iter()
        .zip(want)
        .map(|(g, w)| {
            g.iter()
                .zip(w)
                .map(|(a, b)| (f(*a) - f(*b)).abs())
                .fold(0f32, f32::max)
        })
        .collect();
    per_row.sort_by(|a, b| a.partial_cmp(b).unwrap());
    (*per_row.last().unwrap(), per_row[per_row.len() / 2])
}

fn compare(label: &str, d: &lmg_format::Derived, exp: &Path, verbose: bool) {
    let rows3 = |v: &Vec<[f32; 3]>| v.iter().map(|a| a.to_vec()).collect::<Vec<_>>();
    let rows4 = |v: &Vec<[f32; 4]>| v.iter().map(|a| a.to_vec()).collect::<Vec<_>>();

    for (name, tol_max, tol_med, linear) in FIELDS {
        let (got, width) = match name {
            "xyz" => (rows3(&d.xyz), 3),
            "scaling" => (rows3(&d.scaling), 3),
            _ => (rows4(&d.rotation), 4),
        };
        let want = read_expected(exp, name, width);
        let (mx, med) = errors(&got, &want, linear);
        if verbose {
            println!(
                "{}/{:<9} N={:<7} max={:.4e} median={:.4e}",
                label,
                name,
                got.len(),
                mx,
                med
            );
        }
        assert!(
            mx <= tol_max,
            "{}/{}: max {:e} exceeds {:e}",
            label, name, mx, tol_max
        );
        assert!(
            med <= tol_med,
            "{}/{}: median {:e} exceeds {:e} -- distribution shifted, likely a port bug",
            label, name, med, tol_med
        );
    }
}

fn check(case: &str, expect_variant: Variant) {
    let dir = vectors_dir().join(case);
    let bundle = Bundle::open(&dir.join("bundle.lmg")).expect("open bundle");
    assert_eq!(bundle.meta.variant, expect_variant);

    let d = bundle.derive().expect("derive");
    assert_eq!(d.xyz.len(), bundle.meta.num_splats);

    // Structure the format drops entirely.
    assert_eq!(d.triangle_indices, vec![0, 0, 1, 2, 2, 2]);
    assert_eq!(d.alpha_indices, vec![0, 1, 0, 0, 1, 2]);

    compare(case, &d, &dir.join("expected.safetensors"), false);
}

#[test]
fn binding_matches_python() {
    check("binding", Variant::Binding);
}

#[test]
fn hover_matches_python() {
    check("hover", Variant::Hover);
}

#[test]
fn params_roundtrip_preserves_everything() {
    // Not a byte comparison: safetensors fixes neither header key order nor
    // padding, so two implementations legitimately differ in those bytes.
    // What must survive a rewrite is every tensor and every metadata key.
    let dir = vectors_dir().join("binding/bundle.lmg");
    let bundle = Bundle::open(&dir).expect("open bundle");
    let out = std::env::temp_dir().join("lmg_roundtrip.safetensors");
    write_params(&bundle, &out).expect("write");

    let orig_raw = std::fs::read(dir.join("scene.safetensors")).unwrap();
    let new_raw = std::fs::read(&out).unwrap();
    let a = SafeTensors::deserialize(&orig_raw).unwrap();
    let b = SafeTensors::deserialize(&new_raw).unwrap();

    let mut names_a: Vec<&str> = a.names().into_iter().map(|s| s.as_str()).collect();
    let mut names_b: Vec<&str> = b.names().into_iter().map(|s| s.as_str()).collect();
    names_a.sort();
    names_b.sort();
    assert_eq!(names_a, names_b, "tensor set changed");
    for n in &names_a {
        let (ta, tb) = (a.tensor(n).unwrap(), b.tensor(n).unwrap());
        assert_eq!(ta.dtype(), tb.dtype(), "{}: dtype", n);
        assert_eq!(ta.shape(), tb.shape(), "{}: shape", n);
        assert_eq!(ta.data(), tb.data(), "{}: bytes", n);
    }

    // Metadata this crate does not model (e.g. "source") must not be dropped.
    let reread = Bundle::open(&dir).unwrap();
    let (_, hb) = SafeTensors::read_metadata(&new_raw).unwrap();
    let mdb = hb.metadata().clone().expect("metadata");
    assert_eq!(reread.metadata, mdb, "metadata keys changed on rewrite");
    assert!(mdb.contains_key("source"), "unmodelled key was dropped");
}

#[test]
fn version_gate_is_wired_up() {
    let dir = vectors_dir().join("binding/bundle.lmg");
    let bundle = Bundle::open(&dir).unwrap();
    assert_eq!(bundle.meta.format_version, lmg_format::FORMAT_VERSION);
}

/// Real-data conformance: a real mesh (degenerate faces and all) at 32k splats.
/// The vectors are tens of MB so they are not committed; generate one with
/// `lmg_format.make_vectors.from_full(...)` and point this at it:
///
///     LMG_REAL_VECTOR=/tmp/lmg_real_vector cargo test --release -- --nocapture
#[test]
fn real_checkpoint_matches_python() {
    let dir = match std::env::var("LMG_REAL_VECTOR") {
        Ok(d) => PathBuf::from(d),
        Err(_) => {
            eprintln!("skipped: set LMG_REAL_VECTOR to a generated vector directory");
            return;
        }
    };
    let bundle = Bundle::open(&dir.join("bundle.lmg")).expect("open bundle");
    let d = bundle.derive().expect("derive");
    compare("real", &d, &dir.join("expected.safetensors"), true);
}
